# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: Billy Barnum
description: >- # this means to ignore newlines until "baseurl:"
  Data architecture and stuff.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://billybarnum.github.io" 
repository: "billybarnum/billybarnum.github.io"
remote_theme: "mmistakes/minimal-mistakes"
github: [metadata]

locale: "en-US"
timezone: America/New_York
twitter:
  username: "WilliamGBarnum"
github_username:  billybarnum
paginate: 10 # amount of posts to show
paginate_path: /page:num/

#Author settings for the left sidebar
author:
  name   : "Billy Barnum"
  avatar : "/assets/img/Billy20170924_Blog_Photo_1MB.jpg"
  bio    : "My awesome biography constrained to a sentence or two goes here."
  twitter: "WilliamGBarnum"
  linkedin: "billybarnum"
  github : "billybarnum"
  uri    : # "http://your-site.com"
  home   : # null (default), "absolute or relative url to link to author home"

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
minimal_mistakes_skin: "contrast"
search: true
search_provider: algolia
algolia:
  application_id: YE2XUE0VFN
  index_name: jekyll-blog
  search_only_api_key: a3842892398c2f0116e12fc93da5eab3
  powered_by: false
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

#Front Matter Defaults
defaults:
  # _posts
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
  # _drafts (should be identical to _posts except for scope/path)
  - scope:
      path: "_drafts"
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true

# Include non-default directories in processing
include: ["_pages"]

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
